### ISSUE TITLE
button support

### ISSUE THREAD

**Issue by ninokierulf** [PGSSoft/ParallaxView#1]
ParallaxViewActions is marked internal so I can't create custom UIButton or any other control for that instance

**Comment by nonameplum** [comment]
Sorry but as far as I can see `ParallaxViewActions` is open and all properties related to that class also. Could you provide more informations?

**Comment by ninokierulf** [comment]
the init func is not declared public, so I'm receiving an error saying i cant initialize because it is declared internal

i'm using the library via cocoapods so it's a separate module for me

**Comment by nonameplum** [comment]
Fixed with https://github.com/PGSSoft/ParallaxView/commit/05201cde3ae215d30a0080ec52e62d71424492cf
