### ISSUE TITLE
Lock swipe directions

### ISSUE THREAD

**Issue by RomanPodymov** [PGSSoft/ParallaxView#10]
Hi everybody.
Thank you for this library, I really like it.
Now I want to create buttons to play, buy and rent movie (the same way as it is in the movies iTunes application). As I can see for such buttons user can swipe to the left and to the right only. But now I see that ParallaxView handles all swipes and I don't know how to lock some swipe directions. Could you please help me? Thank you in advance.

**Comment by nonameplum** [comment]
Sorry for the late response. I'm not quite sure what do you mean that `ParralaxView` handles all swipes? You can decide it by the layout and proper utilization of the focus engine which is beyond the `ParallaxView`.
I will close it for now and feel free to open if you still need to address this.
