### ISSUE TITLE
update to swift 4.2

### ISSUE THREAD

**Issue by Radiksidenko** [PGSSoft/ParallaxView#12]

**Comment by tmm1** [comment]
Swift 4 is required to use Xcode 10.2, and Xcode 10.2 is required for all new app submissions

**Comment by Radiksidenko** [comment]
Erm, no, in Xcode 12.1 it can also be used and I have already updated to swift 5 here https://github.com/PGSSoft/ParallaxView/pull/14

**Comment by nonameplum** [comment]
Added Swift 5 support. https://github.com/PGSSoft/ParallaxView/releases/tag/3.0.0
