### ISSUE TITLE
Project not building on 10.2 - please update Swift version

### ISSUE THREAD

**Issue by walsht** [PGSSoft/ParallaxView#15]
Can't build the project on XCode 10.2
```
:-1: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'ParallaxView tvOS')
```

**Comment by Radiksidenko** [comment]
@walsht Hi, look my PR #14

**Comment by cookiezilla** [comment]
Hi, was the PR #14 merge with the master branch? I've used cocoapods to update my project library but i keep getting the old version (the one from 2017). In the main site i keep seeing the old ReadMe too and i see that the latest commit is: 3fa6114 on Jun 7, 2017.

Am i doing something wrong while trying to update my library?

Thanks in advance!

**Comment by Radiksidenko** [comment]
Hi, you are doing everything right just the developers of this Pod are very lazy and can’t do it themselves. My advice, fork it, update it yourself and install it under the link

**Comment by nonameplum** [comment]
Added Swift 5 support https://github.com/PGSSoft/ParallaxView/releases/tag/3.0.0
