### ISSUE TITLE
Weird shaking-effect when focusing ParallaxViews

### ISSUE THREAD

**Issue by MrNiceCat** [PGSSoft/ParallaxView#19]
Hi there,

im getting weird effects on the ParallaxViews on the element that is getting focused in any direction. When focusing element, it is shaking to left and right for a split second.
Doesnt happen with the CollectionViewCells.

Same on the example on "Any View" if you go from the label to the orange element.

**Comment by nonameplum** [comment]
Thank you for your patience.
This is fixed now with the release 3.1.0 (https://github.com/PGSSoft/ParallaxView/releases/tag/3.1.0)
