### ISSUE TITLE
glow image customizability

### ISSUE THREAD

**Issue by ninokierulf** [PGSSoft/ParallaxView#2]
while developing in simulator, the glow seems fine. when viewed in a high res tv, the glow shows aliasing. 

so I was thinking for the original glow image to be rendered using CoreGraphics or 
for a custom glow image to be set.

**Comment by nonameplum** [comment]
Feature added to version `2.0.4` with https://github.com/PGSSoft/ParallaxView/commit/de1533a6e864a2b2c02b1a0a067896dca2e240f3 . Thanks for your valuable comments.
