### ISSUE TITLE
subviewsParallaxMode not working properly in UICollectionViewCell

### ISSUE THREAD

**Issue by stefanomondino** [PGSSoft/ParallaxView#3]
I would like to achieve some subview parallax effect in my custom collection view cells (created in a xib file).
I have a `UIImageView` covering all the cell's space, with some text on top. 
The cell is a `ParallaxCollectionViewCell` subclass, and I'd like to use `.basedOnTag` mode.
This kind of behavior is currently not possible

in
`public func addParallaxMotionEffects(with options: inout ParallaxEffectOptions)` 
the interpolation causing the parallax effect is applied to all the (first level) subviews, but a collection view cell only has one subview (the content view).  All my subviews are inside the system-defined content view, so the intended effect will never be able to work properly.
I'd like to change the `subviews` property used at line 87 (and 120) of UIView+ParallaxEffect 
`  subviews
                .filter { $0 !== options.glowContainerView }
                .enumerated()
                .forEach { (index: Int, subview: UIView) in `

to something like this
`let subviews = (self as? ParallaxCollectionViewCell)?.contentView.subviews ?? self.subviews`

Does this make sense?

**Comment by stefanomondino** [comment]
#4 here's a (almost) non breaking implementation

**Comment by nonameplum** [comment]
@stefanomondino Thanks for you contribution and pr. Instead of using inheritance I would like to stick with composition using existing `ParallaxEffectOptions` struct that is used for this purpose. Please take a look at the changes that I have made and please let me know if that will work you.

https://github.com/PGSSoft/ParallaxView/compare/pr/4

**Comment by stefanomondino** [comment]
Thanks, I total agree with your solution. I'll try it out in few days but seems good to me. Thank you very much:)

**Comment by stefanomondino** [comment]
works like a charm! can you please merge it and release it?

**Comment by nonameplum** [comment]
Feature added with https://github.com/PGSSoft/ParallaxView/releases/tag/2.0.7
