### ISSUE TITLE
ParallaxView v2.0.8

### ISSUE THREAD

**Issue by dcordero** [PGSSoft/ParallaxView#6]
Hello Łukasz,

could it be possible to have a new release of ParallaxView with the changes introduced in this PR?
https://github.com/PGSSoft/ParallaxView/pull/5

Those changes should be 100% backward compatible and it would allow us to start adapting our App to tvOS 11 more easily.

Thanks a lot btw for sharing this great project 🎩

**Comment by nonameplum** [comment]
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  ParallaxView (2.0.8) successfully published
 📅  June 7th, 23:41
 🌎  https://cocoapods.org/pods/ParallaxView
 👍  Tell your friends!
--------------------------------------------------------------------------------
https://github.com/PGSSoft/ParallaxView/releases/tag/2.0.8
