### ISSUE TITLE
Suggestion: canbecomefocused

### ISSUE THREAD

**Issue by ninokierulf** [PGSSoft/ParallaxView#9]
working with collectionView, sometimes you want the collectionViewDelegate to 
decide whether to allow focus or not via 
`func collectionView(_ collectionView: UICollectionView, canFocusItemAt indexPath: IndexPath) -> Bool`

after some time of investigation, I discovered that when a collectionviewcell overrides 
canBecomeFocused, the collectionViewDelegate function
`func collectionView(_ collectionView: UICollectionView, canFocusItemAt indexPath: IndexPath) -> Bool`
doesn't get called.

to solve this issue, I just commented the code
in ParallaxCollectionViewCell, 
```
//open override var canBecomeFocused : Bool {
//        return true
//}
```

**Comment by nonameplum** [comment]
Addressed with https://github.com/PGSSoft/ParallaxView/commit/28963a536a0b026dec7ba0413022268ecf1a9cc5
